### ISSUE TITLE
typo error

### ISSUE THREAD

**Issue by Necktschnagge** [Rav4s/NginX-Config-Files#3]
I suppose it has to be `add_header` rather than `add-header`.
https://github.com/Rav4s/NginX-Config-Files/blob/7308dbdae1ea373672cfec54331e0590608dfe03/reverse-proxy.conf#L75

**Comment by Rav4s** [comment]
Thanks, I will change it

**Comment by Rav4s** [comment]
Fixed in dc583905865880a18a6d5518c2c004c27bdab84c and 357d046164f7f814595be9b1df2d615cb51caca6
